from pydantic import BaseModel
from typing import Any, Optional, Dict

class DocumentChunk(BaseModel):
    """
    Represents a chunk of text extracted from a document.

    This is used during the ingestion and embedding process.
    Each chunk will be embedded and stored in the vector database.
    """

    # The actual text content of the chunk
    # Example: "The Eiffel Tower is located in Paris."
    content: str

    metadata: Optional[Dict[str, Any]] = None
    # Example: {"source": "travel_guides", "page": 5}
    chunk_id: Optional[str] = None

class UserQuery(BaseModel):
    """
    Represents a single user question coming into the Travel Assistant.

    This is the very first object created when a user asks something.
    It acts as a validated input contract for the entire system.
    """

    # The actual question asked by the user
    # Example: "Plan a 5-day trip to Japan"
    query: str

    # Optional session identifier
    # Used later to support conversation memory
    session_id: Optional[str] = None

    # Optional metadata for extra context
    # Example: {"destination": "Japan", "days": 5}
    metadata: Optional[Dict] = None


class AssistantResponse(BaseModel):
    """
    Represents a response generated by the Travel Assistant.

    This object is returned after the system finishes processing
    a user query (including retrieval and generation).
    """
    
    # The main text response to the user
    # Example: "I recommend visiting the Eiffel Tower and Louvre Museum."
    response: str

    # Optional additional information
    # Example: {"attractions": ["Eiffel Tower", "Louvre Museum"]}
    metadata: Optional[Dict] = None   


class RetrievedDocument(BaseModel):
    """
    Represents a single document retrieved from the vector store
    during the RAG (Retrieval-Augmented Generation) process.

    This schema is INTERNAL to the system and is not returned
    directly to the user.
    """

    # The main content of the retrieved document
    # Example: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France."
    content: str

    # Optional metadata about the document
    # Example: {"source": "travel_guides", "id": "doc123"}
    source: Optional[Dict] = None

    # Optional similarity score from vector search
    # Higher usually means more relevant
    score: Optional[float] = None

    # Optional metadata such as page number, section name, etc.
    metadata: Optional[Dict] = None

    